package config

const (
	BotToken = "BOT_TOKEN"

	RABBITMQ_USER       = "RABBITMQ_USER"
	RABBITMQ_PASSWORD   = "RABBITMQ_PASSWORD"
	RABBITMQ_HOST       = "RABBITMQ_HOST"
	RABBITMQ_PORT       = "RABBITMQ_PORT"
	RABBITMQ_VIRT_HOST  = "RABBITMQ_VIRT_HOST"
	RABBITMQ_QUEUE_NAME = "RABBITMQ_QUEUE_NAME"
)

type Config interface {
	GetString(key string) string
}
